### ISSUE TITLE
main.css refers to an idea.svg that does not exist?

### ISSUE THREAD

**Issue by rbrown** [JaJuMa-GmbH/awesome-hyva#1]
This [line](https://github.com/JaJuMa-GmbH/awesome-hyva/blob/d94f72fcc60932bed472b14b12603b5df3114c05/view/adminhtml/web/css/main.css#L21) refers to `../images/idea.svg` but there is no such file? At least I think that's why my logs says 
```
main.ERROR: Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/Jajuma_AwesomeHyva/images/idea.svg'
main.CRITICAL: Unable to resolve the source file for 'adminhtml/Magento/backend/en_US/Jajuma_AwesomeHyva/images/idea.svg'
```

**Comment by JaJuMa** [comment]
Hi @rbrown 

You are right - Thank you very much for reporting this issue!

Fixed with release 2.1.3
