### ISSUE TITLE
Consider adding another github topic: `hyva-icons`

### ISSUE THREAD

**Issue by GrimLink** [JaJuMa-GmbH/awesome-hyva#2]
To make a separation of the more general Hyvä and Magento topics, consider adding another topic named `hyva-icons` this will make it easier for all to find icons packs just for Hyvä use.

**Comment by JaJuMa** [comment]
Thanks for the idea @GrimLink 
Done ✅

**Comment by GrimLink** [comment]
Awesome!

![Screenshot 2023-07-05 at 09 21 04](https://github.com/JaJuMa-GmbH/awesome-hyva/assets/4387541/a4265499-7c86-4eaf-8795-863036220daf)

Sadly the amount of tags clipped it in this repo

**Comment by JaJuMa** [comment]
Fixed
