### ISSUE TITLE
Add $attributes option typehint

### ISSUE THREAD

**Issue by rhoerr** [JaJuMa-GmbH/awesome-hyva#3]
Thanks for the great module!

Could you add the `$attributes` option to the parameter list of all the icon methods?

The icon classes have for instance:
```
 * @method string adHtml(string $classnames = '', ?int $width = null, ?int $height = null)
```

But the underlying `formatHtml()` in Hyva has a fourth `$attributes` parameter available. This is important for instance when providing a title tag, to change the mouseover text from the icon name.

```
    public function renderHtml(
        string $icon,
        string $classNames = '',
        ?int $width = 24,
        ?int $height = 24,
        array $attributes = []
    ): string {
```

Example usage:

```
<?= $awesomeiconssolid->listHtml("w-5 h-5", 25, 25, ['title' => $escaper->escapeHtmlAttr(__('Add to list'))]) ?>
```

Currently this works (because it's a magic method), but PhpStorm doesn't think the parameter exists.

**Comment by JaJuMa** [comment]
Thanks a lot @rhoerr for pointing that out!
Fixed with release 2.1.6
